"""
report_generator.py — Simple, clean PDF report generation for Expense Manager.

Uses ReportLab to produce a professional, easy-to-read PDF with:
- Total expense summary
- Simple list of all expenses (Date, Amount, Category, Description)
- Black and white format only
- No charts or AI-generated styling
"""

from __future__ import annotations

import io
from datetime import datetime
from typing import List, Optional

# ── ReportLab imports ────────────────────────────────────────────────────────
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import (
    BaseDocTemplate,
    Frame,
    PageTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
)

# ── App modules ───────────────────────────────────────────────────────────────
from models import Expense, Budget
from utils import format_currency


# ─────────────────────────────────────────────────────────────────────────────
# Colors - Black and White only
# ─────────────────────────────────────────────────────────────────────────────
_BLACK = colors.HexColor("#000000")
_WHITE = colors.white
_GRAY_LIGHT = colors.HexColor("#F5F5F5")
_GRAY_BORDER = colors.HexColor("#CCCCCC")

# Page geometry
_PAGE_W, _PAGE_H = A4
_M_L  = 15 * mm     # left margin
_M_R  = 15 * mm     # right margin
_M_T  = 15 * mm     # top margin
_M_B  = 15 * mm     # bottom margin
_CW   = _PAGE_W - _M_L - _M_R        # usable content width


# ─────────────────────────────────────────────────────────────────────────────
# Paragraph styles - Simple and professional
# ─────────────────────────────────────────────────────────────────────────────

def _s(name: str, **kw) -> ParagraphStyle:
    if "fontName" not in kw:
        kw["fontName"] = "Helvetica"
    return ParagraphStyle(name, **kw)


_STYLES: dict[str, ParagraphStyle] = {
    "title":       _s("title",       fontSize=18, fontName="Helvetica-Bold",
                       textColor=_BLACK, alignment=TA_CENTER, leading=22),
    "subtitle":    _s("subtitle",    fontSize=11, fontName="Helvetica-Bold",
                       textColor=_BLACK, alignment=TA_CENTER, leading=14),
    "section":     _s("section",     fontSize=12, fontName="Helvetica-Bold",
                       textColor=_BLACK, leading=16, spaceAfter=2),
    "normal":      _s("normal",      fontSize=9,  textColor=_BLACK, leading=12),
    "normal_bold": _s("normal_bold", fontSize=9,  fontName="Helvetica-Bold",
                       textColor=_BLACK, leading=12),
    "label":       _s("label",       fontSize=9,  textColor=_BLACK, leading=12),
    "value":       _s("value",       fontSize=9,  fontName="Helvetica-Bold",
                       textColor=_BLACK, leading=12),
    "table_header":_s("table_header",fontSize=9,  fontName="Helvetica-Bold",
                       textColor=_WHITE, leading=12),
    "table_cell":  _s("table_cell",  fontSize=8,  textColor=_BLACK, leading=11),
    "table_right": _s("table_right", fontSize=8,  textColor=_BLACK,
                       alignment=TA_RIGHT, leading=11),
    "table_center":_s("table_center",fontSize=8,  textColor=_BLACK,
                       alignment=TA_CENTER, leading=11),
}


# ─────────────────────────────────────────────────────────────────────────────
# Page header and footer
# ─────────────────────────────────────────────────────────────────────────────

class _PageDecor:
    """Draw header and footer on every page."""

    def __init__(self) -> None:
        self.total_pages: int = 1

    def __call__(self, canvas, doc) -> None:
        canvas.saveState()
        w, h = A4

        # ── Header ──────────────────────────────────────────────────
        canvas.setLineWidth(1)
        canvas.setStrokeColor(_BLACK)
        canvas.line(_M_L, h - _M_T - 5*mm, w - _M_R, h - _M_T - 5*mm)

        canvas.setFont("Helvetica-Bold", 10)
        canvas.setFillColor(_BLACK)
        canvas.drawString(_M_L, h - _M_T - 3*mm, "Expense & Budget Manager")

        page_str = f"Page {doc.page} of {self.total_pages}"
        canvas.drawRightString(w - _M_R, h - _M_T - 3*mm, page_str)

        # ── Footer ──────────────────────────────────────────────────
        canvas.setLineWidth(0.5)
        canvas.setStrokeColor(_GRAY_BORDER)
        canvas.line(_M_L, _M_B + 8*mm, w - _M_R, _M_B + 8*mm)

        canvas.setFont("Helvetica", 8)
        canvas.setFillColor(_BLACK)
        canvas.drawString(_M_L, _M_B + 5*mm,
                          "Generated by Expense & Budget Manager")
        canvas.drawRightString(w - _M_R, _M_B + 5*mm,
                               datetime.now().strftime("%d %b %Y  %H:%M"))

        canvas.restoreState()


# ─────────────────────────────────────────────────────────────────────────────
# Section builders
# ─────────────────────────────────────────────────────────────────────────────

def _build_summary(
    expenses: List[Expense],
    period_label: str,
) -> list:
    """Build summary section with total expense."""
    story = []
    s = _STYLES

    total = sum(exp.amount for exp in expenses)

    # Summary table
    summary_data = [
        [Paragraph("TOTAL EXPENSES:", s["label"]),
         Paragraph(format_currency(total), s["value"])],
        [Paragraph("Number of Transactions:", s["label"]),
         Paragraph(str(len(expenses)), s["value"])],
        [Paragraph("Period:", s["label"]),
         Paragraph(period_label, s["value"])],
    ]

    summary_table = Table(summary_data, colWidths=[_CW*0.5, _CW*0.5])
    summary_table.setStyle(TableStyle([
        ("FONTNAME",      (0, 0), (0, -1), "Helvetica-Bold"),
        ("FONTSIZE",      (0, 0), (-1, -1), 9),
        ("TEXTCOLOR",     (0, 0), (-1, -1), _BLACK),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
        ("TOPPADDING",    (0, 0), (-1, -1), 8),
        ("LEFTPADDING",   (0, 0), (-1, -1), 0),
        ("RIGHTPADDING",  (0, 0), (-1, -1), 10),
        ("ALIGN",         (1, 0), (1, -1), "RIGHT"),
        ("BOX",           (0, 0), (-1, -1), 0.5, _GRAY_BORDER),
        ("INNERGRID",     (0, 0), (-1, -1), 0.3, _GRAY_BORDER),
    ]))

    story.append(summary_table)
    story.append(Spacer(1, 8*mm))

    return story


def _build_expenses_table(expenses: List[Expense]) -> Table:
    """Build detailed expense table with all information."""
    s = _STYLES

    # Header row
    header = [
        Paragraph("Date", s["table_header"]),
        Paragraph("Category", s["table_header"]),
        Paragraph("Amount (₹)", s["table_header"]),
        Paragraph("Description", s["table_header"]),
    ]

    rows = [header]

    # Add each expense
    for i, exp in enumerate(expenses):
        bg_color = _GRAY_LIGHT if i % 2 == 0 else _WHITE

        rows.append([
            Paragraph(exp.date, s["table_center"]),
            Paragraph(exp.category, s["table_cell"]),
            Paragraph(format_currency(exp.amount), s["table_right"]),
            Paragraph(exp.description or "-", s["table_cell"]),
        ])

    # Set column widths
    col_widths = [_CW*0.15, _CW*0.20, _CW*0.18, _CW*0.47]

    table = Table(rows, colWidths=col_widths, repeatRows=1)
    table.setStyle(TableStyle([
        # Header styling
        ("BACKGROUND",    (0, 0), (-1, 0), _BLACK),
        ("TEXTCOLOR",     (0, 0), (-1, 0), _WHITE),
        ("FONTNAME",      (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE",      (0, 0), (-1, 0), 9),
        ("ALIGN",         (0, 0), (-1, 0), "CENTER"),
        ("TOPPADDING",    (0, 0), (-1, 0), 8),
        ("BOTTOMPADDING", (0, 0), (-1, 0), 8),
        
        # Data rows styling
        ("FONTSIZE",      (0, 1), (-1, -1), 8),
        ("TOPPADDING",    (0, 1), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 1), (-1, -1), 6),
        ("LEFTPADDING",   (0, 1), (-1, -1), 6),
        ("RIGHTPADDING",  (0, 1), (-1, -1), 6),
        
        # Alternating row colors (light gray and white)
        ("ROWBACKGROUNDS",(0, 1), (-1, -1), [_GRAY_LIGHT, _WHITE]),
        
        # Borders
        ("BOX",           (0, 0), (-1, -1), 0.5, _GRAY_BORDER),
        ("INNERGRID",     (0, 0), (-1, -1), 0.3, _GRAY_BORDER),
        
        # Alignment
        ("ALIGN",         (0, 1), (0, -1), "CENTER"),  # Date center
        ("ALIGN",         (1, 1), (1, -1), "LEFT"),    # Category left
        ("ALIGN",         (2, 1), (2, -1), "RIGHT"),   # Amount right
        ("ALIGN",         (3, 1), (3, -1), "LEFT"),    # Description left
        
        ("VALIGN",        (0, 0), (-1, -1), "MIDDLE"),
    ]))

    return table


# ─────────────────────────────────────────────────────────────────────────────
# Document builder
# ─────────────────────────────────────────────────────────────────────────────

def _make_doc(dest, decor: _PageDecor) -> BaseDocTemplate:
    """Create a simple document template."""
    body_top = _M_T + 10*mm
    body_bottom = _M_B + 12*mm
    frame_h = _PAGE_H - body_top - body_bottom

    doc = BaseDocTemplate(
        dest,
        pagesize=A4,
        leftMargin=_M_L,
        rightMargin=_M_R,
        topMargin=body_top,
        bottomMargin=body_bottom,
    )
    frame = Frame(_M_L, body_bottom, _CW, frame_h, id="main")
    doc.addPageTemplates([
        PageTemplate(id="main", frames=[frame], onPage=decor)
    ])
    return doc


def _build_story(
    expenses: List[Expense],
    report_title: str,
    period_label: str,
) -> list:
    """Build the document content."""
    s = _STYLES
    story = []

    # ── Title ───────────────────────────────────────────────────────
    story.append(Spacer(1, 5*mm))
    story.append(Paragraph(report_title, s["title"]))
    story.append(Spacer(1, 2*mm))
    story.append(Paragraph(period_label, s["subtitle"]))
    story.append(Spacer(1, 8*mm))

    # ── Summary Section ─────────────────────────────────────────────
    story.append(Paragraph("Summary", s["section"]))
    story.extend(_build_summary(expenses, period_label))

    # ── Expenses Section ────────────────────────────────────────────
    story.append(Paragraph("All Expenses", s["section"]))
    story.append(_build_expenses_table(expenses))
    story.append(Spacer(1, 5*mm))

    return story


# ─────────────────────────────────────────────────────────────────────────────
# Public entry point
# ─────────────────────────────────────────────────────────────────────────────

def generate_pdf_report(
    expenses: List[Expense],
    budgets: List[Budget],
    filepath: str,
    report_title: str = "Expense Report",
    period_label: str = "",
) -> int:
    """
    Generate a simple, clean PDF report with:
    - Total expenses summary
    - Detailed list of all expenses
    - Black and white format only
    - No charts or colored styling

    Args:
        expenses:     Expense records to include.
        budgets:      Budget records (included for compatibility, not used).
        filepath:     Destination file path (must end in .pdf).
        report_title: Title shown in the report header.
        period_label: Human-readable period (e.g. "August 2026").

    Returns:
        Number of expense records written.

    Raises:
        ValueError:      If *expenses* is empty.
        PermissionError: If the file cannot be written.
        Exception:       Re-raised on any ReportLab error.
    """
    if not expenses:
        raise ValueError("No expense data to include in the report.")

    if not period_label:
        dates = [e.date for e in expenses]
        period_label = f"{min(dates)}  to  {max(dates)}"

    decor = _PageDecor()

    # ── Pass 1: Dry run to count pages ──────────────────────────────
    buf = io.BytesIO()
    story = _build_story(expenses, report_title, period_label)
    dry_doc = _make_doc(buf, decor)
    dry_doc.build(story)
    decor.total_pages = dry_doc.page

    # ── Pass 2: Real build to file ───────────────────────────────────
    story = _build_story(expenses, report_title, period_label)
    real_doc = _make_doc(filepath, decor)
    real_doc.build(story)

    return len(expenses)
